### ISSUE TITLE
Hide Sort By Price option whe catalog option is enabled

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/woocommerce-catalog-enquiry#1]
- WooCommerce displays a sorting option low to high price or High to low price
![Screenshot](https://user-images.githubusercontent.com/28754174/67615041-b2730f80-f7e4-11e9-9622-1d2549f44bc8.png)

-Now, if the catalog is enabled, then these sort options can be disabled? 

Enhancement request link - https://wc-marketplace.com/support-forum/topic/sort-by-price-still-visible/

**Comment by itzmekhokan** [comment]
@moumitahalder Fixed in v3.2.2
