### ISSUE TITLE
Migration Issue with new plugin

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/woocommerce-catalog-enquiry#15]
- Catalog Mode
Old : https://prnt.sc/u798rq
New : https://prnt.sc/u79963

- Product enquiry, Pop up disable, remove price
Old : https://prnt.sc/u79jgu
New : https://prnt.sc/u79jrp
         https://prnt.sc/u79jz6

None of the settings of older plugin is carried into the new plugin.

**Comment by cool-raju** [comment]
Need a fresh testing
