### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by sbn111** [wcmarketplace/woocommerce-catalog-enquiry#17]
Where is the documentation about hooks in this plugin?

**Comment by purnendudash** [comment]
We are currently working on a major release, where will be changing the plugin structure and hooks & filters list too. Would request you to check the beta version of the plugin for the same.

**Comment by sbn111** [comment]
Okay. I need to edit the woocommerce-catalog-enquiry/classes/class-wc-Woocommerce-Catalog-Enquiry-frontend.php file. Can you please tell me how can it be achieved?

Thank you
