### ISSUE TITLE
Editing File

### ISSUE THREAD

**Issue by sbn111** [wcmarketplace/woocommerce-catalog-enquiry#18]
Hi Sir,
I need to edit the woocommerce-catalog-enquiry/classes/class-wc-Woocommerce-Catalog-Enquiry-frontend.php file. Can you please tell me how can it be achieved?

Thank you

**Comment by cool-raju** [comment]
Hi @sbn111 
As because this is a class file so it's not recommended to add any code here. If required then remove any hook and add it again to your currently active theme functions.php file.

**Comment by sbn111** [comment]
> 
> 
> Hi @sbn111
> As because this is a class file so it's not recommended to add any code here. If required then remove any hook and add it again to your currently active theme functions.php file.

Can you please tell me how to do that?

**Comment by cool-raju** [comment]
Here is the link of remove action https://developer.wordpress.org/reference/functions/remove_action/ and add action https://developer.wordpress.org/reference/functions/add_action/
