### ISSUE TITLE
email not going to additional emails id added

### ISSUE THREAD

**Issue by srutakirty** [wcmarketplace/woocommerce-catalog-enquiry#29]
Recreate the issue : add extra email id to the additional email id fields and then submit the enquiry form.
No email is send to the additional email id.

Thread link : https://wordpress.org/support/topic/problem-enquiry-form-only-sent-to-admin-and-reply-sent-to-additional-mails/

**Comment by cool-raju** [comment]
@srutakirty and @abhirup97, please recheck

**Comment by srutakirty** [comment]
The email is going as you can see here https://www.loom.com/share/18986f3ab9954cdbb3825eed5bbb1969
