### ISSUE TITLE
Enquiry forum page loading

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/woocommerce-catalog-enquiry#5]
fill the form and security code correctly, everything is ok and msg will send. But if I did any mistake or didn't fill correctly the security code then appear the white screen of the dead with an infinity loading circle and nothing happened.

https://www.loom.com/share/100342f63e8e4176aedc0901877341ff

**Comment by xakefreud** [comment]
When you leave one field empty, it will do this. (loading gif) just keeps on spinning
